table Date
	dataCategory: Time
	lineageTag: aaaa1111-1111-1111-1111-111111111111

	column date_sk
		dataType: int64
		isHidden
		summarizeBy: none
		sourceColumn: date_sk
		lineageTag: aaaa1111-1111-1111-1111-111111111112

	column Date
		dataType: dateTime
		formatString: Short Date
		isKey
		summarizeBy: none
		sourceColumn: Date
		lineageTag: aaaa1111-1111-1111-1111-111111111113

	column Year
		dataType: int64
		summarizeBy: none
		sourceColumn: Year
		lineageTag: aaaa1111-1111-1111-1111-111111111114

	column 'Month Name'
		dataType: string
		summarizeBy: none
		sourceColumn: Month Name
		lineageTag: aaaa1111-1111-1111-1111-111111111115

	partition Date = m
		mode: import
		queryGroup: Dimensions
		source =
				let
				    Source = date_dim_src,
				    #"Renamed Columns" = Table.RenameColumns(Source,{{"month_name", "Month Name"}})
				in
				    #"Renamed Columns"

	annotation PBI_ResultType = Table
