table Measure
	lineageTag: eeee5555-5555-5555-5555-555555555555

	measure 'Total Sales' = SUM ( Sales_fct[amount] )
		formatString: \$#,0
		displayFolder: Sales
		lineageTag: eeee5555-5555-5555-5555-555555555556

	measure 'Total Cost' = SUM ( Sales_fct[cost] )
		formatString: \$#,0
		displayFolder: Sales
		lineageTag: eeee5555-5555-5555-5555-555555555557

	measure 'Total Quantity' = SUM ( Sales_fct[quantity] )
		formatString: #,0
		displayFolder: Sales
		lineageTag: eeee5555-5555-5555-5555-555555555558

	measure 'Margin' = [Total Sales] - [Total Cost]
		formatString: \$#,0
		displayFolder: Profitability
		lineageTag: eeee5555-5555-5555-5555-555555555559

	measure 'Margin %' = DIVIDE ( [Margin], [Total Sales] )
		formatString: 0.0%;-0.0%;0.0%
		displayFolder: Profitability
		lineageTag: eeee5555-5555-5555-5555-55555555555a

	measure 'Sales by Ship Date' =

			CALCULATE (
			    [Total Sales],
			    USERELATIONSHIP ( Sales_fct[ship_date_fk], Date[date_sk] )
			)
		formatString: \$#,0
		displayFolder: Sales
		lineageTag: eeee5555-5555-5555-5555-55555555555b

	measure 'VIP Customer Sales' =

			CALCULATE (
			    [Total Sales],
			    FILTER ( Customer, Customer[Segment] = "VIP" )
			)
		formatString: \$#,0
		displayFolder: Sales
		lineageTag: eeee5555-5555-5555-5555-55555555555c

	partition Measure = m
		mode: import
		source = ```
				let
				    Source = #table({"Placeholder"}, {{1}})
				in
				    Source
				```

	annotation PBI_ResultType = Table
